# Generated by Django 5.0.1 on 2024-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_post_likes_users_post_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_like',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
