# Generated by Django 5.0.1 on 2024-02-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
