# Generated by Django 5.0.1 on 2024-02-19 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_follow_following_follow_followed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='followed_user',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed_user')},
        ),
    ]
