# Generated by Django 5.0.1 on 2024-02-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_followers_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
